services:
  redox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redox
    environment:
      RUST_LOG: debug
    ports:
      - "8080:8080"
    mem_limit: 4096m
    mem_reservation: 4096m
    cpus: 4.0
    cpu_count: 4

  bun:
    build:
      context: ./examples/bun
      dockerfile: Dockerfile
    container_name: bun
    ports:
      - "8081:8081"
    mem_limit: 2048m
    mem_reservation: 2048m
    cpus: 4.0
    cpu_count: 4

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_user
      POSTGRES_DB: hr
    volumes:
      - ./examples/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    user: root
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  # https://www.jaegertracing.io/docs/next-release/deployment/#:~:text=At%20default%20settings%20jaeger%2Dcollector%20exposes%20the%20following%20ports%3A
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "16687:16687"
      - "4317:4317"
      - "4318:4318"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
      - "14250:14250"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      LOG_LEVEL: debug
      COLLECTOR_OTLP_ENABLED: true
volumes:
  prometheus-data:
  grafana-data: